### ISSUE TITLE
Regarding Query Messages

### ISSUE THREAD

**Issue by codearth01** [remidomingues/ASTra#2] opened 2018-09-06 05:57 UTC
To get info about a particular edge in Graph, we write command COO edge(i) where i can be any integer.
Here edge1 is the key of edgeDict or key has been defined in some other way.

**Comment by remidomingues** [comment] 2018-09-06 06:43
Yes, edges are identified by their edge ID which you can find in `graph.graphDict` and `graph.edgesDict`. These IDs are defined by SUMO, so if you are already displaying a SUMO network, you should already have these indexes.
If not, most commands from the graph functionality will return the list of IDs, e.g. `SUC` or `LEN`.

You may be interested in reading this, it's not a detailed doc like you can file in the comments of the source files, but it could answer a few high level questions you may still have: https://github.com/remidomingues/ASTra/blob/master/ASTra.pdf

I'm closing this issue since everything seems to be working as designed, but you may comment again in this thread should you have other questions.

**Closed as completed by remidomingues** 2018-09-06 06:43 UTC
