### ISSUE TITLE
Regarding Run of Astra

### ISSUE THREAD

**Issue by codearth01** [remidomingues/ASTra#1] opened 2018-09-02 05:35 UTC
Hi,
I am Ashutosh. Can you please explain to me how to make all the programs run? Every time after I run manager.py and connect to ports, the threads, that have been started, start to close. I am also not able to figure out what is the client here and how to interact with server.

**Comment by remidomingues** [comment] 2018-09-03 06:48
Hello Ashutosh,

This API provides high level functionalities to interact with the traffic simulator SUMO. You should install and launch SUMO prior to the execution of manager.py.
The logs should give you detailed information about what problem might still occur.

Also, don't forget to update the following constants in `astra/constants.py`:
POSIX_OS = {True,False}
ASTRA_DIRECTORY = <ASTRA_ABSOLUTE_DIRECTORY>
SUMO_TOOLS_DIRECTORY = <SUMO_TOOLS_DIRECTORY>
SUMO_BINARY = <SUMO_BINARY_FILE_PATH>
DUAROUTER_BINARY = <DUAROUTER_BINARY_FILE_PATH>

**Comment by codearth01** [comment] 2018-09-03 11:39
I have updated all those values. But the problem is after ASTRA is started, it immediately starts to close all started threads.

Graph >>> Importing graph...
Graph >>> Done
Graph >>> Importing junctions dictionary...
Graph >>> Done
Graph >>> Importing edges dictionary...
Graph >>> Done
Manager >>> --------- Graph enabled --------
Manager >>> Waiting for connection on 127.0.0.1:18001...
Manager >>> Connected
Manager >>> Waiting for connection on 127.0.0.1:18002...
Manager >>> Connected
Manager >>> ------- Routing enabled --------
Manager >>> Waiting for connection on 127.0.0.1:18003...
Manager >>> Connected
Manager >>> Waiting for connection on 127.0.0.1:18004...
Manager >>> Connected
Manager >>> -------- Vehicles enabled --------
Manager >>> Waiting for connection on 127.0.0.1:18005...
Manager >>> Connected
Manager >>> Waiting for connection on 127.0.0.1:18006...
Manager >>> Connected
Manager >>> ---- Traffic lights enabled ----
Manager >>> Waiting for connection on 127.0.0.1:18007...
Manager >>> Connected
Manager >>> Waiting for connection on 127.0.0.1:18008...
Manager >>> Connected
Manager >>> ------ Simulation enabled -------
Manager >>> Waiting for connection on 127.0.0.1:18009...
C:\Program Files (x86)\DLR\Sumo\tools\traci\domain.py:112: UserWarning: The domain trafficlights is deprecated, use trafficlight instead.
  self._name, self._deprecatedFor))  # , DeprecationWarning)
Manager >>> Connected
TrafficLights >>> Importing traffic lights dictionary...
TrafficLights >>> Done
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Started app 'ASTra'                                      +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Graph >>> Shutting down current thread
WARNING : Route >>> Invalid command received: ['COO']
Vehicle >>> Shutting down current thread
Route >>> Shutting down current thread
TrafficLights >>> Shutting down current thread

**Comment by remidomingues** [comment] 2018-09-03 12:11
I see, this means that the relaunch mutex has been released by the other threads:
https://github.com/remidomingues/ASTra/blob/master/astra/manager.py#L248
The thread holding this mutex is simulation: https://github.com/remidomingues/ASTra/blob/master/astra/simulation.py

I'm concerned by the warning you get. It is possible that the warning you get causes the trafficlight thread to shutdown, which creates a cascade of shutdowns to restart the API. I would suggest either to disable the trafficlight functionality (`TLL_ENABLED = False` in the constants file) or to downgrade traci to use a compatible version (this API was tested for SUMO 0.16.

**Comment by codearth01** [comment] 2018-09-03 16:45
I tried both ways, still the same 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Initializing app 'ASTra'                                 +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Manager >>> Starting a SUMO instance using Dublin network...
Manager >>> Done
Manager >>> Initializing TraCI on port 8813...
Manager >>> Initialized
Graph >>> Importing graph...
Graph >>> Done
Graph >>> Importing junctions dictionary...
Graph >>> Done
Graph >>> Importing edges dictionary...
Graph >>> Done
Manager >>> --------- Graph enabled --------
Manager >>> Waiting for connection on 127.0.0.1:18001...
Manager >>> Connected
Manager >>> Waiting for connection on 127.0.0.1:18002...
Manager >>> Connected
Manager >>> ------- Routing enabled --------
Manager >>> Waiting for connection on 127.0.0.1:18003...
Manager >>> Connected
Manager >>> Waiting for connection on 127.0.0.1:18004...
Manager >>> Connected
Manager >>> -------- Vehicles enabled --------
Manager >>> Waiting for connection on 127.0.0.1:18005...
Manager >>> Connected
Manager >>> Waiting for connection on 127.0.0.1:18006...
Manager >>> Connected
Manager >>> === Traffic lights disabled ====
Manager >>> ------ Simulation enabled -------
Manager >>> Waiting for connection on 127.0.0.1:18009...
Manager >>> Connected
TrafficLights >>> Importing traffic lights dictionary...
TrafficLights >>> Done
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Started app 'ASTra'                                      +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Vehicle >>> Shutting down current thread
Route >>> Shutting down current thread
Graph >>> Shutting down current thread

**Comment by remidomingues** [comment] 2018-09-03 18:05
Indeed, that's unexpected. At least the warning disappeared, so it shouldn't be a compatibility issue.
Usually, the API will trigger an automatic relaunch when any thread encounter a serious failure, but this is not the case here. 
Can you add the following line [here](https://github.com/remidomingues/ASTra/blob/master/astra/vehicle.py#L483)?
`Logger.exception(e)`
To be sure, you can also do it for `route.py` and `graph.py`. This behavior denotes an issue with the communication with the SUMO interface, [TraCI](http://sumo.dlr.de/wiki/TraCI).

**Comment by codearth01** [comment] 2018-09-03 18:43
In the exception, it is saying that the socket was closed-

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Started app 'ASTra'                                      +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Vehicle >>> Shutting down current thread
Route >>> Shutting down current thread
Traceback (most recent call last):
Graph >>> Shutting down current thread
  File "F:\ASTRA\ASTra-master\astra\vehicle.py", line 395, in run
    raise constants.ClosedSocketException("The distant socket has been closed")
constants.ClosedSocketException: The distant socket has been closed
Traceback (most recent call last):
  File "F:\ASTRA\ASTra-master\astra\route.py", line 173, in run
    raise constants.ClosedSocketException("The distant socket has been closed")
constants.ClosedSocketException: The distant socket has been closed
Traceback (most recent call last):
  File "F:\ASTRA\ASTra-master\astra\graph.py", line 675, in run
    raise constants.ClosedSocketException("The distant socket has been closed")
constants.ClosedSocketException: The distant socket has been closed

**Comment by remidomingues** [comment] 2018-09-03 18:51
I see. The problem is not on this side then, it's actually TraCI which closes the connections for some reason. Can you confirm that you are using SUMO 0.16.0? If yes, I don't see where the issue could come from.

**Comment by codearth01** [comment] 2018-09-04 04:53
Yah, I am using SUMO 0.16.0. Is there no other way to make it run?

**Comment by remidomingues** [comment] 2018-09-04 07:06
Everything looks fine on this side, the API is working as designed and you shouldn't encounter any issue with your version of SUMO. Unfortunately, I don't know why TraCI is closing sockets in your environment, this is the first time this problem is reported.

**Comment by codearth01** [comment] 2018-09-05 05:01
# Sending a ready message to the remote client
        eManagerReady.set()

What is the remote client here?

**Comment by remidomingues** [comment] 2018-09-05 06:57
eManagerReady is only a Python thread event, used to synchronize between threads.
Regarding remote clients, Astra only communicates with TraCI, the SUMO API, through sockets.

**Comment by codearth01** [comment] 2018-09-05 07:21
graphInputSocket = acceptConnection(constants.HOST, constants.GRAPH_INPUT_PORT) graphOutputSocket = acceptConnection(constants.HOST, constants.GRAPH_OUTPUT_PORT).

Here do I need to write a client side  which establishes connection to this port?

**Comment by remidomingues** [comment] 2018-09-05 07:48
Yes, the communication works this way:
your_custom_client <-> ASTra <-> TraCI <-> SUMO
ASTra waits for your connections from port 18001 to 18009. Each pair of ports will expose a high-level functionality, e.g. graph queries, shortest path query, traffic light management... The sockets to query to access these functionalities can be specified in the [constants file](https://github.com/remidomingues/ASTra/blob/master/astra/constants.py). Connections must be performed in ascending order (from the lowest port to the highest).
The message format is then described in each file. For example, for graph queries, it's in the [graph.py ](https://github.com/remidomingues/ASTra/blob/master/astra/graph.py) file.
I should have written a separate detailed documentation to explain this.
I hope it helps.

**Comment by codearth01** [comment] 2018-09-05 07:51
So at each port, there should be a client continuously sending messages.

**Comment by remidomingues** [comment] 2018-09-05 07:55
Not continuously, each thread corresponding to each functionality is waiting for a query from your custom client.
But actually, according to your log files, all the connections are established with the sockets. So I assumed you had a dedicated client initializing these connections. If not, you may change the ports to access a free range which will be used by your custom client.

**Comment by codearth01** [comment] 2018-09-05 10:53
Can you send me your code of how you are establishing all connections in your deployThreads method?
I just need the threads to keep running so that I could query.
I think somehow the connections are not being made properly and  after starting all threads, it is hitting exceptions in each thread and going to (in graph.py)

        except Exception as e:
            if e.__class__.__name__ == constants.CLOSED_SOCKET_EXCEPTION or e.__class__.__name__ == constants.TRACI_EXCEPTION:
                Logger.info("{}Shutting down current thread".format(constants.PRINT_PREFIX_GRAPH))
                Logger.exception(e)
                sys.exit()
            else:
                Logger.error("{}A {} exception occurred:".format(constants.PRINT_PREFIX_GRAPH, e.__class__.__name__))
                Logger.exception(e)

**Comment by remidomingues** [comment] 2018-09-05 11:30
I haven't used this API in a while, so I can't send you any code using it. But client side, this is fairly simple:
```
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("host", port))
```
The only problem that you have, is located at the server side (ASTra) socket creation:
https://github.com/remidomingues/ASTra/blob/master/astra/manager.py#L52
`accept` is a blocking call, so it waits for the connection to be established by the client. In the log, you see the following trace, which means that a client opened a connection. If you didn't, the port may be used by another application, change the ports in the constants file until ASTra blocks on "Waiting for connection". Then, you'll have to connect from your custom client.
```
Manager >>> Waiting for connection on 127.0.0.1:18001...
Manager >>> Connected
```

**Comment by codearth01** [comment] 2018-09-05 11:55
During socket creation, it is running as required but as soon as all the sockets are created each of them starts to close one by one. Do I need to keep the sockets open all the time to keep the threads running?

**Comment by remidomingues** [comment] 2018-09-05 12:14
Based on your comment, I assume that you have indeed some dedicated code which connects to the sockets. ASTra is built in order to be robust, so as soon as one functionality will fail, the whole API will restart in order to be fully working. 

After having connected to all the sockets, are you closing the connections? If yes, this is definitively the cause of your issue. If you don't want to use a functionality, and thus don't want to create dedicated sockets, just disable it in the constants file. Sockets must be kept opened at all time. ASTra threads have no reason to run it they can't receive commands through sockets anymore.

Should I close this issue?

**Comment by codearth01** [comment] 2018-09-05 12:25
I will try to sort out the problem. Thanks for your time.

**Closed as completed** 2018-09-05 12:37 UTC
